In [1]:
import numpy as np

In [2]:
# Create two 2x2 NumPy arrays and calculate their product using the np.
# matmul() function

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

product = np.matmul(array1, array2)

print("First array:")
print(array1)
print()

print("Second array:")
print(array2)
print()

print("Product of the two arrays:")
print(product)

First array:
[[1 2]
 [3 4]]

Second array:
[[5 6]
 [7 8]]

Product of the two arrays:
[[19 22]
 [43 50]]


In [4]:
# Create two 3x3 NumPy arrays and calculate their product using the 
# np.dot() function.

array1 = np.array([[1, 2,3], [4 , 5, 6],[7, 8, 9]])
array2 = np.array([[10, 11, 12], [13, 14, 15],[16, 17, 18]])

product = np.dot(array1, array2)

print("First array:")
print(array1)
print()

print("Second array:")
print(array2)
print()

print("Product of the two arrays:")
print(product)

First array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Second array:
[[10 11 12]
 [13 14 15]
 [16 17 18]]

Product of the two arrays:
[[ 84  90  96]
 [201 216 231]
 [318 342 366]]


In [5]:
# Create a 2x3 NumPy array and a 3x2 NumPy array, and calculate their
# product using the np.matmul() function.


array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8],
                   [9, 10],
                   [11, 12]])


product = np.matmul(array1, array2)
print(product)


[[ 58  64]
 [139 154]]


In [6]:
# Create a 3x2 NumPy array and a 2x3 NumPy array, and calculate
# their product using the np.dot() function

array1 = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])


array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

product = np.dot(array1, array2)
print(product)


[[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]]


In [7]:
# Create a 4x4 NumPy array and its transpose using the np.transpose() function,
# then calculate their product using the np.matmul() function.

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

arr_transposed = np.transpose(arr)
product = np.matmul(arr, arr_transposed)

print("Original Array:")
print(arr)
print("\nTranspose of the Array:")
print(arr_transposed)
print("\nProduct of the Array and its Transpose:")
print(product)



Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Transpose of the Array:
[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]

Product of the Array and its Transpose:
[[ 30  70 110 150]
 [ 70 174 278 382]
 [110 278 446 614]
 [150 382 614 846]]
