In [2]:
import numpy as np

In [19]:
# create a 2x2 NumPy array and multiply it by 2.

arr1 = np.arange(4).reshape(2,2)
print(arr1)
print('\n')

mult = arr1*2
print(mult)

[[0 1]
 [2 3]]


[[0 2]
 [4 6]]


In [21]:
# create a 3x3 NumPy array and add 5 to each element.

arr1 = np.arange(1,10).reshape(3,3)
print(arr1)
print('\n')

add = arr1+5
print(add)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [31]:
# create a 4x4 NumPy array and subtract to each element.

arr1 = np.arange(1,17).reshape(4,4)
print(arr1)
print('\n')

row_means = np.mean(arr1, axis=1, keepdims=True)
print("\nMean of each row:")
print(row_means)

arr_subtracted = arr1 - row_means
print("\nSubtract the mean of each row from each element:")
print(arr_subtracted)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]



Mean of each row:
[[ 2.5]
 [ 6.5]
 [10.5]
 [14.5]]

Subtract the mean of each row from each element:
[[-1.5 -0.5  0.5  1.5]
 [-1.5 -0.5  0.5  1.5]
 [-1.5 -0.5  0.5  1.5]
 [-1.5 -0.5  0.5  1.5]]


In [34]:
# create a 5x5 NumPy array and divide each element by 2.

arr1 = np.arange(1,26).reshape(5,5)
print(arr1)
print('\n')

divi = arr1/2
print(divi)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


[[ 0.5  1.   1.5  2.   2.5]
 [ 3.   3.5  4.   4.5  5. ]
 [ 5.5  6.   6.5  7.   7.5]
 [ 8.   8.5  9.   9.5 10. ]
 [10.5 11.  11.5 12.  12.5]]


In [36]:
# create a 6x6 NumPy array and calculate the square root of each element.

arr1 = np.arange(1,37).reshape(6,6)
print(arr1)
print('\n')

sqrt1 = np.sqrt(arr1)
print(sqrt1)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


[[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.         3.16227766 3.31662479 3.46410162]
 [3.60555128 3.74165739 3.87298335 4.         4.12310563 4.24264069]
 [4.35889894 4.47213595 4.58257569 4.69041576 4.79583152 4.89897949]
 [5.         5.09901951 5.19615242 5.29150262 5.38516481 5.47722558]
 [5.56776436 5.65685425 5.74456265 5.83095189 5.91607978 6.        ]]
